# Roberts Lab
# Aquatic & Fishery Sciences
# University of Washington
# Bioinformatics Image

## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #
# List of bioinformatics software in this image #
## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #

#################################
# SOFTWARE		VERSION 		#
#################################
# bedtools		2.26.0  		#
# bismark		0.15.0  		#
# blast			2.4.0+  		#
# bowtie1		1.1.2			#
# bowtie2		2.2.8   		#
# bsmap			2.90    		#
# cufflinks		2.1.1   		#
# dammit						#
# jupyter						#
# miniconda		2				#
# multiqc		0.8				#
# fastqc		0.11.5  		#
# fastx_toolkit	0.0.13  		#
# R				3.3.1   		#
# RStudioServer	1.0.44			#
# pyrad			3.0.66  		#
# samtools		0.1.19  		#
# stacks		1.40    		#
# tophat		2.1.1   		#
# trimmomatic	0.36    		#
# trinity		2.2.0			#
# vcftools		0.1.14	#
## ## ## ## ## ## ## ## ## ## ## 



FROM debian:8
MAINTAINER Sam White <samwhite@uw.edu>


# Get software dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    apt-utils \
    locales \
    debconf \
    libc6 \
    default-jdk \
    software-properties-common \
    build-essential \
    pkg-config \
    libncurses-dev \
    ncurses-dev \
    libncurses5-dev \
    libncursesw5-dev \
    libpng12-0 \
    zlib1g-dev \
    dialog \
    sudo \
    nano \
    curl \
    git \
    man \
    unzip \
    bzip2 \
    wget \
    automake \
    gfortran \
    gcc-multilib \
    gobjc++ \
    aptitude \
    xorg-dev \
    texinfo \
    libsparsehash-dev \
    gdebi-core \
    libapparmor1 \
    libssl1.0.0 \
    libedit2 \
    libcurl4-openssl-dev \
    libssl-dev \
    psmisc \
    python-setuptools \
    net-tools \
    sqlite3 \
	infernal \
	liburi-escape-xs-perl \
	emboss \
	liburi-perl \
	ruby \
	hmmer \
	libsm6 \
	libxrender1 \
	libfontconfig1 \
	parallel \
	locales-all \
	libzmq3-dev \
	libpango1.0-dev \
	tree \
	htop \
    && apt-get clean

    
RUN aptitude update && \
    aptitude install -y \
    libreadline-dev
    
# Set the locale
#RUN locale-gen en_US.UTF-8
#RUN dpkg-reconfigure locales
#RUN sed -i '/en_US.UTF-8 UTF-8/c\en_US.UTF-8 UTF-8' /etc/locale.gen
#ENV LANG en_US.UTF-8
#ENV LANGUAGE en_US.UTF-8
#ENV LC_ALL en_US.UTF-8

# Make bioinformatics directory
RUN mkdir /usr/local/bioinformatics

# Set working directory
WORKDIR /usr/local/bioinformatics

# Add bioinformatics directory to PATH
# ENV PATH /usr/local/bioinformatics:$PATH

# Install MiniConda (for installing Jupyter Notebook)
RUN wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh \
	&& bash Miniconda2-latest-Linux-x86_64.sh -b \
	&& (cd /root/miniconda2/bin && ./conda update conda -y) \
	&& rm Miniconda2-latest-Linux-x86_64.sh

ENV PATH /root/miniconda2/bin:$PATH

# Install bedtools (v2.26.0)
RUN wget https://github.com/arq5x/bedtools2/releases/download/v2.26.0/bedtools-2.26.0.tar.gz \
	&& tar -zxvf bedtools-2.26.0.tar.gz \
	&& make -C /usr/local/bioinformatics/bedtools2 \
	&& rm bedtools-2.26.0.tar.gz

ENV PATH /usr/local/bioinformatics/bedtools2:$PATH

## Add MiniConda channel to allow easy install of khmer (dammit dependency)
RUN conda config --add channels ged --add channels bioconda

## Install Python dependencies for use in dammit
RUN conda install setuptools pandas khmer doit nose ficus matplotlib numexpr scipy numpy

## Update pandas and numexpr using MiniConda (dammit dependencies)
RUN conda update pandas numexpr
    
# Install blast (v2.4.0+)
RUN wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.4.0/ncbi-blast-2.4.0+-x64-linux.tar.gz \
	&& tar -zxvpf ncbi-blast-2.4.0+-x64-linux.tar.gz \
	&& rm ncbi-blast-2.4.0+-x64-linux.tar.gz

ENV PATH /usr/local/bioinformatics/ncbi-blast-2.3.0+/bin:$PATH

# Install bowtie2 (v2.2.8)
RUN wget --output-document=bowtie2-2.2.8-linux-x86_64.zip \
	https://sourceforge.net/projects/bowtie-bio/files/bowtie2/2.2.8/bowtie2-2.2.8-linux-x86_64.zip/download \
	&& unzip bowtie2-2.2.8-linux-x86_64.zip \
	&& rm bowtie2-2.2.8-linux-x86_64.zip

ENV PATH /usr/local/bioinformatics/bowtie2-2.2.8:$PATH

# Install cufflinks (v2.1.1)
RUN wget http://cole-trapnell-lab.github.io/cufflinks/assets/downloads/cufflinks-2.1.1.tar.gz \
	&& tar -zxvf cufflinks-2.1.1.tar.gz \
	&& rm cufflinks-2.1.1.tar.gz

ENV PATH /usr/local/bioinformatics/cufflinks-2.1.1:$PATH

# Install FastQC (v0.11.5)
RUN wget http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.5.zip \
	&& unzip fastqc_v0.11.5.zip \
	&& chmod 755 /usr/local/bioinformatics/FastQC/fastqc \
	&& rm fastqc_v0.11.5.zip

ENV PATH /usr/local/bioinformatics/FastQC:$PATH
	
# Install samtools0.1.19 (version required for use with Stacks)
RUN wget --output-document=samtools-0.1.19.tar.bz2 \
	http://sourceforge.net/projects/samtools/files/samtools/0.1.19/samtools-0.1.19.tar.bz2/download \
	&& tar -xjf samtools-0.1.19.tar.bz2 \
	&& make -C /usr/local/bioinformatics/samtools-0.1.19/ \
	&& rm samtools-0.1.19.tar.bz2

# Install tophat (v2.1.1)
RUN wget https://ccb.jhu.edu/software/tophat/downloads/tophat-2.1.1.Linux_x86_64.tar.gz \
	&& tar -zxvf tophat-2.1.1.Linux_x86_64.tar.gz \
	&& rm tophat-2.1.1.Linux_x86_64.tar.gz

ENV PATH /usr/local/bioinformatics/tophat-2.1.1.Linux_x86_64:$PATH

# Install trimmomatic (v0.36)
RUN wget http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/Trimmomatic-0.36.zip \
	&& unzip Trimmomatic-0.36.zip \
	&& echo 'alias trimmomatic="java -jar /usr/local/bioinformatics/Trimmomatic-0.36/trimmomatic-0.36.jar"' >> ~/.bashrc \
	&& rm Trimmomatic-0.36.zip

# Install fastx toolkit (v0.0.13)
RUN wget http://hannonlab.cshl.edu/fastx_toolkit/fastx_toolkit_0.0.13_binaries_Linux_2.6_amd64.tar.bz2 \
	&& mkdir /usr/local/bioinformatics/fastx_toolkit \
	&& tar -xjf fastx_toolkit_0.0.13_binaries_Linux_2.6_amd64.tar.bz2 -C /usr/local/bioinformatics/fastx_toolkit \
	&& rm fastx_toolkit_0.0.13_binaries_Linux_2.6_amd64.tar.bz2

ENV PATH /usr/local/bioinformatics/fastx_toolkit/bin:$PATH

# Install bismark (v0.15.0)
RUN wget http://www.bioinformatics.babraham.ac.uk/projects/bismark/bismark_v0.15.0.tar.gz \
	&& tar -xzf bismark_v0.15.0.tar.gz \
	&& rm bismark_v0.15.0.tar.gz

ENV PATH /usr/local/bioinformatics/bismark_v0.15.0:$PATH

# Install bsmap (v2.90)
RUN wget http://lilab.research.bcm.edu/dldcc-web/lilab/yxi/bsmap/bsmap-2.90.tgz \
	&& tar -xzf bsmap-2.90.tgz \
	&& (cd /usr/local/bioinformatics/bsmap-2.90 && exec make && make install) \
	&& rm bsmap-2.90.tgz

ENV PATH /usr/local/bioinformatics/bsmap-2.90:$PATH

# Install pyrad (v3.0.66)
RUN wget https://github.com/dereneaton/pyrad/archive/3.0.66.tar.gz \
	&& tar -xzf 3.0.66.tar.gz \
	&& (cd /usr/local/bioinformatics/pyrad-3.0.66 && exec python setup.py install && pyrad -h) \
	&& rm 3.0.66.tar.gz

ENV PATH /usr/local/bioinformatics/pyrad-3.0.66:$PATH


# Install muscle (v3.8.31)
# pyrad dependency
RUN wget http://www.drive5.com/muscle/downloads3.8.31/muscle3.8.31_i86linux64.tar.gz \
	&& tar -xzf muscle3.8.31_i86linux64.tar.gz \
	&& rm muscle3.8.31_i86linux64.tar.gz

ENV PATH /usr/local/bioinformatics/muscle3.8.31_i86linux64:$PATH

# Install vsearch (v1.11)
# pyrad dependency
RUN wget https://github.com/torognes/vsearch/releases/download/v1.11.1/vsearch-1.11.1-linux-x86_64.tar.gz \
	&& tar -xzf vsearch-1.11.1-linux-x86_64.tar.gz \
	&& rm vsearch-1.11.1-linux-x86_64.tar.gz

ENV PATH /usr/local/bioinformatics/vsearch-1.11.1-linux-x86_64/bin:$PATH

# Install pear
# pyrad dependency
RUN wget http://sco.h-its.org/exelixis/web/software/pear/files/pear-0.9.6-bin-64.tar.gz \
	&& tar -xzf pear-0.9.6-bin-64.tar.gz \
	&& rm pear-0.9.6-bin-64.tar.gz

ENV PATH /usr/local/bioinformatics/pear-0.9.6-bin-64:$PATH

# Install Stacks (v.1.40)
RUN wget http://catchenlab.life.illinois.edu/stacks/source/stacks-1.40.tar.gz \
	&& tar -xzf stacks-1.40.tar.gz \
	&& (cd /usr/local/bioinformatics/stacks-1.40 && ./configure --enable-sparsehash --enable-bam --with-bam-include-path=/usr/local/bioinformatics/samtools-0.1.19/ --with-bam-lib-path=/usr/local/bioinformatics/samtools-0.1.19/ && make -j 4 && make install) \
	&& rm stacks-1.40.tar.gz

## Install Jupyter Notebook & all dependencies (via MiniConda)
# Creates config file
# Sets browser to FALSE
# Sets default IP address to 0.0.0.0; uses \x27 to set single quotes
# Sets browser token (so no password needed to access notebooks) to blank; uses \x27 to set single quotes
RUN conda install jupyter -y \
	&& jupyter notebook --generate-config \
	&& (sed -i '/c.NotebookApp.open_browser/c\c.NotebookApp.open_browser = False' /root/.jupyter/jupyter_notebook_config.py) \
	&& (sed -i '/c.NotebookApp.ip/c\c.NotebookApp.ip = \x270.0.0.0\x27' /root/.jupyter/jupyter_notebook_config.py) \
	&& (sed -i '/c.NotebookApp.token/c\c.NotebookApp.token = u\x27\x27' /root/.jupyter/jupyter_notebook_config.py)

## Install dammit
RUN conda install dammit

## Install MultiQC (v.0.8)
RUN wget https://github.com/ewels/MultiQC/archive/v0.8.tar.gz \
	&& tar -xzf v0.8.tar.gz \
	&& (cd /usr/local/bioinformatics/MultiQC-0.8 && exec python setup.py install) \
	&& rm /usr/local/bioinformatics/v0.8.tar.gz

##Install Trinity (v.2.2.0)
RUN wget https://github.com/trinityrnaseq/trinityrnaseq/archive/v2.2.0.tar.gz \
	&& tar -xzf v2.2.0.tar.gz \
	&& (cd /usr/local/bioinformatics/trinityrnaseq-2.2.0 && make && make plugins) \
	&& rm /usr/local/bioinformatics/v2.2.0.tar.gz

ENV PATH /usr/local/bioinformatics/trinityrnaseq-2.2.0:$PATH

# Install bowtie-1 (v.1.1.2; this version required for Trinity)
RUN wget --output-document=bowtie-1.1.2-linux-x86_64.zip \
	https://sourceforge.net/projects/bowtie-bio/files/bowtie/1.1.2/bowtie-1.1.2-linux-x86_64.zip/download \
	&& unzip bowtie-1.1.2-linux-x86_64.zip \
	&& rm bowtie-1.1.2-linux-x86_64.zip
	
ENV PATH /usr/local/bioinformatics/bowtie-1.1.2:$PATH

# Create srlab user
RUN useradd -ms /bin/bash srlab \
        && echo "srlab:rstudio" | chpasswd

# Install R (v3.3.1 1)
RUN conda install -c r r-base='3.3.1 1'

# Install R Essentials (v1.4.3)
RUN conda install -c r r-essentials=1.4.3

# Install RStudio Server (v1.0.44)
RUN wget https://download2.rstudio.org/rstudio-server-1.0.44-amd64.deb \
        && gdebi --non-interactive rstudio-server-1.0.44-amd64.deb \
        && echo "alias rstudio-server='/etc/init.d/rstudio-server'" >> ~/.bashrc \
        && rm rstudio-server-1.0.44-amd64.deb

# Install R kernel for Jupyter notebooks
#RUN touch kernel_script_temp.R

#RUN echo '#!/usr/local/bioinformatics/R-3.2.5/bin/Rscript' >> kernel_script_temp.R \
#	&& echo 'install.packages(c("crayon", "pbdZMQ", "devtools"), repos = "http://cran.us.r-project.org")' >> kernel_script_temp.R \
#	&& echo 'devtools::install_github(paste0("IRkernel/", c("repr", "IRdisplay", "IRkernel")))' >> kernel_script_temp.R \
# 	&& echo 'IRkernel::installspec(user = FALSE)' >> kernel_script_temp.R

#RUN /usr/local/bioinformatics/R-3.2.5/bin/Rscript kernel_script_temp.R

## Install vcftools (v0.1.14)
RUN wget https://github.com/vcftools/vcftools/releases/download/v0.1.14/vcftools-0.1.14.tar.gz \
	&& tar -xzf vcftools-0.1.14.tar.gz \
	&& (cd /usr/local/bioinformatics/vcftools-0.1.14 && ./configure && make && make install) \
	&& rm vcftools-0.1.14.tar.gz

ENV PATH /usr/local/bioinformatics/vcftools-0.1.14:$PATH

# Install rpy2 for R magics in Jupyter Notebooks (v2.8.1)
RUN conda install -c r rpy2=2.8.1


# Expose ports for RStudio Server & Jupyter Notebook, respectively
EXPOSE 8787 8888
